<a href="https://colab.research.google.com/github/DhruvThakral/Python-Data-Science-Machine-Learning-Course/blob/main/Lecture_15_Data_Manipulation_And_Analysis_With_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Data Manipulation and Analysis with NumPy**

**Definition:** NumPy is a fundamental package for scientific computing with Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures. NumPy arrays are more efficient and provide better performance for numerical operations compared to Python's built-in lists.

**Use Case in Real Life:** NumPy can be used in various scientific computing scenarios, such as statistical analysis, signal processing, and image processing.

Array object in numpy is called ndarray




**Creating a NumPy Array from a List**

In [45]:
!pip install numpy

In [46]:
import numpy as np  # aliasing numpy as np

# Creating a 1D array from the List
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

# Creating a 2D array from the List
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # it consists of 1D arrays as its elements
print(arr2)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## **Creating array with functions**

In [47]:
#Creating an array of zeros

zeros = np.zeros((3,3))      #First argument is number of rows and second is number of columns
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [48]:
#Creating an  array of ones

ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
#Creating an array with a range of values

range_arr = np.arange(10,20,2)  #First argument is start value, second is end value which is exclusive also and third is step value
print(range_arr)

[10 12 14 16 18]


In [50]:
#Creating an array with random values
random_arr = np.random.rand(3,3)    #This will give the random floating point numbers from 0 to 1
print(random_arr)

[[0.98270504 0.33067485 0.70969767]
 [0.09328    0.48456865 0.24047926]
 [0.07845873 0.36209717 0.95787444]]


# **Basic Array Operations - Element Wise Operations**

In [51]:
arr = np.array([1,2,3,4,5])

#Element - wise addition
print(arr+2)

[3 4 5 6 7]


In [52]:
#Element - wise subtraction
print(arr-2)

[-1  0  1  2  3]


In [53]:
#Element - wise multiplication
print(arr*2)

[ 2  4  6  8 10]


In [54]:
#Element - wise division
print(arr/2)

[0.5 1.  1.5 2.  2.5]


# **Basic Array Operations - Mathematical Operations**

In [55]:
arr = np.array([1,2,3,4,5,6])

#Square Root
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [56]:
#Exponential
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [57]:
#Logarithmic
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [58]:
#Sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


# **Indexing and Slicing - Indexing**

In [59]:
arr = np.array([1,2,3,4,5])

print(arr[0]) #First element
print(arr[-1]) #Last element
print(arr[-2]) #LastSecond Element

1
5
4


# **Indexing and Slicing - Slicing**

---



In [60]:
arr = np.array([1,2,3,4,5])

print(arr[1:4])  #Elements from index 1 to 3
print(arr[:3])   #Elements from start upto index 2
print(arr[2:])   #Elements from index 2 to end

[2 3 4]
[1 2 3]
[3 4 5]


# **Indexing and Slicing - Advanced Indexing**

In [61]:
arr = np.array([1,2,3,4,5])

#Boolean Indexing
print(arr[arr > 3])

#Fancy Indexing
indices = [0, 2, 4]
print(arr[indices])

[4 5]
[1 3 5]


# **Reshaping the arrays**

In [62]:
arr = np.array([[1,2,3] , [4,5,6]])

reshaped_array = arr.reshape(3,2)   #Total no of elements must remain constant
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


# **Transposing the arrays**

In [63]:
arr = np.array([[1,2,3],[4,5,6]])

transposed_array = arr.T
print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


# **Aggregation Function - Sum and Mean**

In [64]:
arr = np.array([[1,2,3],[4,5,6]])

#Sum of all the elements of an array
sum = np.sum(arr)
print(sum)

21


In [65]:
#Column wise sum
sum = np.sum(arr,axis=0)
print(sum)

[5 7 9]


In [66]:
#Row wise sum
sum = np.sum(arr,axis=1)
print(sum)

[ 6 15]


In [67]:
# Mean
mean = np.mean(arr)
print(mean)

3.5


# **Aggregate Functions - Min and Max**

In [68]:
arr = np.array([[1,2,3],[4,5,6]])

#Maximum
max = np.max(arr)
print(max)

6


In [69]:
#Minimum
min = np.min(arr)
print(min)

1


In [70]:
#Index of a minimum value
index = np.argmin(arr)

print(index)

0


In [71]:
#Index of a maximum value
index = np.argmax(arr)

print(index)

5
